config/routes.rb
# frozen_string_literal: true

require 'api_constraints'

Rails.application.routes.draw do
  apipie
  devise_for :users, controllers: { registrations: 'user/registrations' }
  as :user do
    get 'user/profile' => 'users/registrations#edit', as: :user_profile
    put 'user/update_profile' => 'users/registrations#update_profile', as: :update_user_profile
    put 'user/update_account' => 'users/registrations#update', as: :update_user_account
    post 'invitation/create_user' => 'users/registrations#create_user_from_invitation', :as => 'create_user_from_invitation'
  end

  # You can have the root of your site routed with "root"
  root 'home#show'

  resources :organizations do
    member do
      put :switch
    end
  end
  get 'organization_wizzard/new_account', to: 'organization_wizzard#new_account', as: :new_account_organization
  get 'organization_wizzard/new_category', to: 'organization_wizzard#new_category', as: :new_category_organization
  post 'organization_wizzard/default_account', to: 'organization_wizzard#create_default_accounts', as: :default_account_organization
  post 'organization_wizzard/default_category', to: 'organization_wizzard#create_default_categories', as: :default_category_organization
  patch 'organization_wizzard/create_accounts', to: 'organization_wizzard#create_accounts', as: :create_accounts_organization
  patch 'organization_wizzard/create_categories', to: 'organization_wizzard#create_categories', as: :create_categories_organization
  resources :statistics, only: :index do
    get :income_by_customers, on: :collection, as: :income_by_customers
    get :expense_by_customers, on: :collection, as: :expense_by_customers
    get :income_by_categories, on: :collection, as: :income_by_categories
    get :expense_by_categories, on: :collection, as: :expense_by_categories
    get :totals_by_customers, on: :collection, as: :totals_by_customers
    get :balances_by_customers, on: :collection, as: :balances_by_customers
    get :balance, on: :collection, as: :balance
    get :customers_chart, on: :collection, as: :customers_chart
  end
  resources :bank_accounts, except: :show do
    put :hide, on: :member
    put :sort, on: :collection
  end
  resources :categories, except: :show
  resources :transactions,  only: %i[new create edit update destroy] do
    post :transfer, action: :create_transfer, on: :collection
  end
  resources :members, only: %i[index edit update destroy]
  resources :customers, except: :show do
    get 'autocomplete', on: :collection
  end
  resources :invoices do
    get 'unpaid', on: :collection
    resources :invoice_items, except: :show
  end
  resources :invitations, only: %i[new create]
  resources :organization_invitations, only: %i[new create destroy]
  get '/invitation/:token/accept' => 'invitations#accept', as: :accept_invitation
  get '/organization_invitation/:token/resend' => 'organization_invitations#resend', as: :resend_organization_invitation
  get '/unsubscribes/:token' => 'unsubscribes#activate', as: :activate_unsubscribe
  mount ActionCable.server => '/cable'

  # API
  namespace :api, defaults: { format: 'json' } do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      devise_for :users, skip: :sessions, controllers: { passwords: 'api/v1/passwords' }
      resources :users, only: %i[update destroy] do
        put :update_profile, on: :member
      end
      post :auth_token, to: 'auth_token#create'

      get :user_info, to: 'users#current'
      resources :currencies, only: %i[index]

      resources :organizations, only: %i[show index create update destroy] do
        resources :bank_accounts, only: %i[show index create update destroy] do
          get :visible, on: :collection
          put :position, action: :update_position, on: :member
        end
        resources :categories, only: %i[show index create update destroy]
        resources :customers, only: %i[show index create update destroy]
        resources :transactions, only: %i[show index create update destroy] do
          post :transfer, action: :create_transfer, on: :collection
          get :summary, on: :collection
        end
        resources :members, only: %i[index show update destroy] do
          get :current
        end
        get :member_info, to: 'members#current'
        put :last_visit, to: 'members#update_last_visit'
        resources :invoices, only: %i[index show create update destroy] do
          get :unpaid, on: :collection
          get 'unpaid/count' => :unpaid_count, on: :collection
        end
        get :total_balances, on: :member
        resources :organization_invitations, only: %i[index show create destroy] do
          post :resend, on: :member
        end
        resources :debtors, only: :index
        resource :statistic, only: [] do
          get :balance
          get :income_categories
          get :expense_categories
          get :income_customers
          get :expense_customers
          get :totals_by_customers
          get :balances_by_customers
          get :income_customers_by_months
          get :expense_customers_by_months
        end
      end
    end
  end
end

app/helpers/layout_helper.rb
# frozen_string_literal: true

module LayoutHelper
  def active_org(org)
    (org.id == current_organization.id ? 'active' : '')
  end

  def colorize_transaction(transaction)
    css_class = transaction.transfer? || transaction.transfer_out? ? 'transfer' : colorize_amount(transaction.amount)
    if params[:controller] == 'home' && current_member && current_member.last_visited_at
      css_class += ' new-transaction' if transaction.created_at > current_member.last_visited_at
    end
    css_class
  end

  def show_amount_with_tooltip(amount, default_currency)
    cb = Money.default_bank
    def_curr = default_currency
    show_tooltip_with_text("#{amount.currency}/#{def_curr}, rate: #{cb.get_rate(amount.currency, def_curr).round(4)}, by #{l cb.rates_updated_at}")
  end

  def show_tooltip_with_text(text)
    content_tag(
      :span, '',
      title: text,
      class: 'glyphicon glyphicon-question-sign exchange-helper',
      data:  { toggle: 'tooltip', placement: 'top' }
    )
  end

  def submit_title
    if params['action'] == 'new'
      'Create'
    else
      'Update'
    end
  end

  def invoices_debt(debtor)
    str =
      if debtor.is_a?(Customer)
        h("#{debtor.name}:")
      else
        'All customers:'
      end
    cb = Money.default_bank
    def_curr = current_organization.default_currency
    debtor.invoices.unpaid.group(:currency).sum(:amount_cents).each do |currency, amount_cents|
      m = Money.new(amount_cents, currency)

      if def_curr == currency
        str += " #{m.format};"
      else
        str += " #{m.format} (#{m.exchange_to(def_curr).format} "
        str += show_tooltip_with_text("#{currency}/#{def_curr}, \
          rate: #{cb.get_rate(currency, def_curr).round(4)}, by #{l cb.rates_updated_at}")
        str += ');'
      end
    end

    str.html_safe # rubocop:disable Rails/OutputSafety
  end

  def total_invoices_debt
    str = '<strong>Total: '
    total = current_organization.total_invoice_debt
    str += total.to_s
    str += '</strong>'
    str.html_safe # rubocop:disable Rails/OutputSafety
  end

  def transaction_type_id(transaction)
    "##{transaction.get_type}"
  end
end

app/views/shared/layout/_flash_messages.html.slim
.flash-messages
  - if notice.present?
    .alert.alert-success
      button type="button" class="close" data-dismiss="alert" aria-hidden="true"
        | &times;
      = notice
  - if alert.present?
    .alert.alert-danger
      button type="button" class="close" data-dismiss="alert" aria-hidden="true"
        | &times;
      = alert

app/views/shared/layout/_head.html.slim
head
  meta charset="utf-8"
  meta http-equiv="X-UA-Compatible" content="IE=edge"
  meta name="viewport" content="width=device-width, initial-scale=1.0"
  title Cashbox
  = Gon::Base.render_data({})
  = stylesheet_link_tag 'application', media: 'all'
  = javascript_include_tag 'application'
  = csrf_meta_tags

app/views/shared/layout/_header.html.slim
header
  nav.navbar.navbar-inverse
    .container-fluid
      .navbar-header
        - if signed_in?
          button.navbar-toggle data-target="#collapse-btn" data-toggle="collapse" type="button"
            span.icon-bar
            span.icon-bar
            span.icon-bar
        = active_link_to 'CashBox', root_path, class: 'navbar-brand', active: :exclusive

      - if signed_in?
        #collapse-btn.collapse.navbar-collapse
          ul.nav.navbar-nav
            = render 'shared/layout/menu_organization'
            = render 'shared/layout/total_balance'
          ul.nav.navbar-nav.navbar-right
            - if current_organization
              = active_link_to 'Invoices', invoices_path, wrap_tag: :li, active: [['invoices']]
              = active_link_to 'Statistics', statistics_path, wrap_tag: :li, active: [['statistics']]
            li.dropdown
              = link_to '#', class: 'dropdown-toggle', data: {toggle: 'dropdown'} do
                #current_user
                  = current_user
                  b.caret
              ul.dropdown-menu
                li= link_to 'Change organization', organizations_path
                li= link_to 'Edit Profile', user_profile_path
                li= link_to 'Send invite', new_invitation_path
                li= link_to 'Sign out', destroy_user_session_path, method: :delete

app/views/shared/layout/_menu_organization.html.slim
- if current_organization
  li.dropdown
    = link_to '#', class: 'dropdown-toggle', data: {toggle: 'dropdown'} do
      #current_organization
        = current_organization
        b.caret
    ul.dropdown-menu
      li= active_link_to 'Details', organization_path(current_organization), wrap_tag: :li, active: [['organizations']]
      li= active_link_to 'Customers', customers_path, wrap_tag: :li, active: [['customers']]
      li= active_link_to 'Bank accounts', bank_accounts_path, wrap_tag: :li, active: [['bank_accounts']]
      li= active_link_to 'Categories', categories_path, wrap_tag: :li, active: [['categories']]
      li= active_link_to 'Members', members_path, wrap_tag: :li, active: [['members', 'invitations']]
      li= active_link_to 'Invoices', invoices_path, wrap_tag: :li, active: [['invoices']]

app/views/shared/layout/_total_balance.html.slim
- if current_organization
  - total_amount = Money.new(0, current_organization.default_currency)

  - content_for :dropdown_menu do
    - Dictionaries.currencies.each_with_index do |curr, i|
      - total = current_organization.bank_accounts.total_balance(curr)
      - total_amount = total_amount + total.exchange_to(current_organization.default_currency)

      li.no-wrap class=colorize_ba_amount(total)
        => money_with_symbol total
        - if curr != current_organization.default_currency
          span.no-wrap
            =<> "(#{money_with_symbol total.exchange_to(current_organization.default_currency)}"
            = show_amount_with_tooltip(total, current_organization.default_currency) + ')'

  li.dropdown.dropdown-total#total_balance
    a.dropdown-toggle data-target="#dropdown-total" data-toggle="dropdown" href="#"
      = "Total: #{money_with_symbol total_amount}"
      b.caret
    ul.dropdown-menu
      = yield :dropdown_menu