config/routes.rb
# frozen_string_literal: true

require 'api_constraints'

Rails.application.routes.draw do
  apipie
  devise_for :users, controllers: { registrations: 'user/registrations' }
  as :user do
    get 'user/profile' => 'users/registrations#edit', as: :user_profile
    put 'user/update_profile' => 'users/registrations#update_profile', as: :update_user_profile
    put 'user/update_account' => 'users/registrations#update', as: :update_user_account
    post 'invitation/create_user' => 'users/registrations#create_user_from_invitation', :as => 'create_user_from_invitation'
  end

  # You can have the root of your site routed with "root"
  root 'home#show'

  resources :organizations do
    member do
      put :switch
    end
  end
  get 'organization_wizzard/new_account', to: 'organization_wizzard#new_account', as: :new_account_organization
  get 'organization_wizzard/new_category', to: 'organization_wizzard#new_category', as: :new_category_organization
  post 'organization_wizzard/default_account', to: 'organization_wizzard#create_default_accounts', as: :default_account_organization
  post 'organization_wizzard/default_category', to: 'organization_wizzard#create_default_categories', as: :default_category_organization
  patch 'organization_wizzard/create_accounts', to: 'organization_wizzard#create_accounts', as: :create_accounts_organization
  patch 'organization_wizzard/create_categories', to: 'organization_wizzard#create_categories', as: :create_categories_organization
  resources :statistics, only: :index do
    get :income_by_customers, on: :collection, as: :income_by_customers
    get :expense_by_customers, on: :collection, as: :expense_by_customers
    get :income_by_categories, on: :collection, as: :income_by_categories
    get :expense_by_categories, on: :collection, as: :expense_by_categories
    get :totals_by_customers, on: :collection, as: :totals_by_customers
    get :balances_by_customers, on: :collection, as: :balances_by_customers
    get :balance, on: :collection, as: :balance
    get :customers_chart, on: :collection, as: :customers_chart
  end
  resources :bank_accounts, except: :show do
    put :hide, on: :member
    put :sort, on: :collection
  end
  resources :categories, except: :show
  resources :transactions,  only: %i[new create edit update destroy] do
    post :transfer, action: :create_transfer, on: :collection
  end
  resources :members, only: %i[index edit update destroy]
  resources :customers, except: :show do
    get 'autocomplete', on: :collection
  end
  resources :invoices do
    get 'unpaid', on: :collection
    resources :invoice_items, except: :show
  end
  resources :invitations, only: %i[new create]
  resources :organization_invitations, only: %i[new create destroy]
  get '/invitation/:token/accept' => 'invitations#accept', as: :accept_invitation
  get '/organization_invitation/:token/resend' => 'organization_invitations#resend', as: :resend_organization_invitation
  get '/unsubscribes/:token' => 'unsubscribes#activate', as: :activate_unsubscribe
  mount ActionCable.server => '/cable'

  # API
  namespace :api, defaults: { format: 'json' } do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      devise_for :users, skip: :sessions, controllers: { passwords: 'api/v1/passwords' }
      resources :users, only: %i[update destroy] do
        put :update_profile, on: :member
      end
      post :auth_token, to: 'auth_token#create'

      get :user_info, to: 'users#current'
      resources :currencies, only: %i[index]

      resources :organizations, only: %i[show index create update destroy] do
        resources :bank_accounts, only: %i[show index create update destroy] do
          get :visible, on: :collection
          put :position, action: :update_position, on: :member
        end
        resources :categories, only: %i[show index create update destroy]
        resources :customers, only: %i[show index create update destroy]
        resources :transactions, only: %i[show index create update destroy] do
          post :transfer, action: :create_transfer, on: :collection
          get :summary, on: :collection
        end
        resources :members, only: %i[index show update destroy] do
          get :current
        end
        get :member_info, to: 'members#current'
        put :last_visit, to: 'members#update_last_visit'
        resources :invoices, only: %i[index show create update destroy] do
          get :unpaid, on: :collection
          get 'unpaid/count' => :unpaid_count, on: :collection
        end
        get :total_balances, on: :member
        resources :organization_invitations, only: %i[index show create destroy] do
          post :resend, on: :member
        end
        resources :debtors, only: :index
        resource :statistic, only: [] do
          get :balance
          get :income_categories
          get :expense_categories
          get :income_customers
          get :expense_customers
          get :totals_by_customers
          get :balances_by_customers
          get :income_customers_by_months
          get :expense_customers_by_months
        end
      end
    end
  end
end

app/models/bank_account.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: bank_accounts
#
#  id              :integer          not null, primary key
#  name            :string(255)      not null
#  description     :string(255)
#  balance_cents   :integer          default(0), not null
#  currency        :string(255)      default("USD"), not null
#  organization_id :integer          not null
#  created_at      :datetime
#  updated_at      :datetime
#  deleted_at      :datetime
#  visible         :boolean          default(TRUE)
#  position        :integer
#  invoice_details :text
#

class BankAccount < ApplicationRecord
  acts_as_list
  acts_as_paranoid

  belongs_to :organization, inverse_of: :bank_accounts
  has_many :transactions, dependent: :destroy, inverse_of: :bank_account
  has_many :invoices, dependent: :destroy, inverse_of: :bank_account

  attr_writer :residue_cents

  monetize :balance_cents, with_model_currency: :currency
  monetize :residue_cents, with_model_currency: :currency

  scope :visible,     ->{ where(visible: true) }
  scope :by_currency, ->(currency){ where('bank_accounts.currency' => currency) if currency.present? }
  scope :positioned,  ->{ order(position: :asc) }

  validates :name,     presence: true
  validates :balance,  presence: true, numericality: { less_than_or_equal_to: Dictionaries.money_max }
  validates :residue,  presence: true, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: Dictionaries.money_max }
  validates :currency, presence: true, inclusion: { in: Dictionaries.currencies, message: '%{value} is not a valid currency' }

  after_create :set_initial_residue
  after_touch :recalculate_amount!

  def residue_cents
    @residue_cents ||= 0
  end

  def residue=(value)
    @residue_cents =
      if value
        value.class == String ? value.delete(',').delete('.') : value
      else
        0
      end
  end

  def self.total_balance(currency)
    Money.new(where(currency: currency).sum(:balance_cents), currency)
  end

  def recalculate_amount!
    update(balance: Money.new(transactions.sum(:amount_cents), currency))
  end

  def set_initial_residue
    transactions.create(amount_cents: residue_cents, transaction_type: 'Residue') if residue.positive?
  end

  def to_s
    "#{name.truncate(30)} (#{Money::Currency.new(currency).symbol})"
  end

  class << self
    def grouped_by_currency(def_currency)
      currencies = Currency.ordered(def_currency)
      all.group_by(&:currency).sort_by do |ba|
        currencies.index(ba.first)
      end
    end

    def create_defaults(organization)
      [*DEFAULT_VALUES[:bank_accounts]].each do |account|
        organization.bank_accounts.find_or_create_by(
          name: account
        )
      end
    end
  end
end

app/controllers/api/v1/bank_accounts_controller.rb
# frozen_string_literal: true

module Api::V1
  class BankAccountsController < BaseOrganizationController
    before_action :set_bank_account, only: %i[show update destroy update_position]

    def_param_group :bank_account do
      param :bank_account, Hash, required: true, action_aware: true do
        param :name, String, 'Name', required: true
        param :description, String, 'Description'
        param :currency, String, 'Currency', required: true
        param :residue, Integer, 'Residue', required: true
        param :invoice_details, String, 'Invoice Details'
      end
    end

    api :GET, '/organizations/:organization_id/bank_accounts', 'Return bank accounts for current organization'
    def index
      @bank_accounts = current_organization.bank_accounts.positioned
    end

    api :GET, '/organizations/:organization_id/bank_accounts/visible', 'Return visible bank accounts for current organization'
    def visible
      @bank_accounts = current_organization.bank_accounts.visible.positioned
      render :index
    end

    api :GET, '/organizations/:organization_id/bank_accounts/:id', 'Return bank account'
    def show
    end

    api :POST, '/organizations/:organization_id/bank_accounts', 'Create bank account'
    param_group :bank_account, BankAccountsController
    def create
      @bank_account = current_organization.bank_accounts.build bank_account_params
      if @bank_account.save
        render :show
      else
        render json: @bank_account.errors, status: :unprocessable_entity
      end
    end

    api :PUT, '/organizations/:organization_id/bank_accounts/:id', 'Update bank account'
    param_group :bank_account, BankAccountsController
    def update
      if @bank_account.update(bank_account_params)
        render :show
      else
        render json: @bank_account.errors, status: :unprocessable_entity
      end
    end

    api :DELETE, '/organizations/:organization_id/bank_accounts/:id', 'Destroy bank account'
    def destroy
      @bank_account.destroy
      render :show
    end

    api :PUT, '/organizations/:organization_id/bank_accounts/:id/position', 'Update bank account position'
    def update_position
      @bank_account.insert_at(update_bank_account_position_params[:position]&.to_i)
      render :show
    end

    private

    def set_bank_account
      @bank_account = current_organization.bank_accounts.find(params[:id])
    end

    def bank_account_params
      params.fetch(:bank_account, {}).permit(:name, :description, :currency, :residue, :invoice_details, :visible)
    end

    def update_bank_account_position_params
      params.fetch(:bank_account, {}).permit(:position)
    end
  end
end

app/controllers/bank_accounts_controller.rb
class BankAccountsController < ApplicationController
  layout 'settings'
  before_action :set_bank_account, only: [:edit, :update, :destroy, :hide]
  before_action :require_organization, only: [:edit, :update, :new, :create,
    :destroy, :hide]
  before_action :redirect_for_not_ready_organization, only: [:edit, :update, :new, :create,
    :destroy, :hide]
  before_action :find_bank_account, only: :sort
  after_action :update_last_viewed_at, only: [:create]

  def new
    @bank_account = current_organization.bank_accounts.build
  end

  def index
    @bank_accounts = current_organization.bank_accounts.positioned
    gon.curr_org_ordered_curr = current_organization.ordered_curr
  end

  def edit
  end

  def create
    @bank_account = current_organization.bank_accounts.build(bank_account_params)

    if @bank_account.save
      redirect_to bank_accounts_path, notice: 'Bank account was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @bank_account.update(bank_account_params)
      redirect_to bank_accounts_path, notice: 'Bank account was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def hide
    @bank_account.toggle!(:visible)
    redirect_to bank_accounts_path
  end

  def destroy
    @bank_account.destroy
    redirect_to bank_accounts_path
  end

  def sort
    authorize @bank_account.organization, :update?

    @bank_account.insert_at(params[:position].to_i)
    render nothing: true
  end

  private
    def find_bank_account
      @bank_account = BankAccount.find(params[:id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_bank_account
      @bank_account = current_organization.bank_accounts.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bank_account_params
      params.require(:bank_account).permit(:name, :description, :currency, :residue, :invoice_details)
    end
end

app/views/bank_accounts/_bank_account.html.slim
h1 Listing bank accounts

- if @bank_accounts.present?
  table.table.table-stripped.table-hover
    thead
      tr
        th Name
        th[style="width:30%"] Description
        th Balance
    tbody
      - @bank_accounts.each do |bank_account|
        tr
          td = bank_account.name
          td = bank_account.description
          td = money_without_cents_and_with_symbol bank_account.balance
          - if @organization.present?
            td = link_to 'Edit', edit_organization_bank_account_path(@organization, bank_account)
            td = link_to 'Destroy', [@organization, bank_account], data: {confirm: 'Are you sure?'}, method: :delete
- else
  .alert.alert-warning No bank accounts

app/views/bank_accounts/_form.html.slim
.row
  .col-sm-6
    = simple_form_for(@bank_account) do |f|
      = f.error_notification

      .form-inputs
        = f.input :name, autofocus: true
        = f.input :description
        = f.input :invoice_details
        - unless f.object.persisted?
          = f.input :residue, input_html: { class: 'amount' }
        = f.input :currency, collection: Currency.ordered, include_blank: false

      .form-actions
        = f.button :submit_with_disable, class: 'btn-primary'

app/views/bank_accounts/edit.html.slim
.page-header
  h1 Editing bank account

== render 'form'

= link_to 'Back', :back

= content_for :sidebar
  = render 'home/settings'

app/views/bank_accounts/index.html.slim
.page-header
  .pull-right
    = link_to 'New bank account', new_bank_account_path, class: 'btn btn-success'
  h1 Listing bank accounts

- if @bank_accounts.present?
  .bank-accounts
    - @bank_accounts.grouped_by_currency(current_organization.default_currency).each do |curr_with_accounts|
      table.table.table-stripped.table-hover.responsive-table data-min=8 data-max=18
        thead
          tr
            th.col-sm-2 Name
            th.col-sm-2 Description
            th.col-sm-2 Balance
            th.col-sm-3 Invoice Details
            th
        tbody id="#{curr_with_accounts.first.downcase}-accounts" data-url=sort_bank_accounts_path
          - curr_with_accounts.last.each do |bank_account|
            tr.item id=dom_id(bank_account) data-item-id=bank_account.id class=colorize_amount(bank_account.balance) data-start-position=bank_account.position
              td.word-break = bank_account.to_s
              td.word-break = bank_account.description
              td = money_with_symbol bank_account.balance
              td.word-break = bank_account.invoice_details
              td
                - if current_organization.present?
                  .btn-group.pull-right
                    = link_to 'Edit', edit_bank_account_path(bank_account),
                      class: 'btn btn-default btn-sm'
                    - if bank_account.visible?
                      = link_to 'Hide', hide_bank_account_path(bank_account),
                        method: :put, class: 'btn btn-warning btn-sm', data: { disable_with: 'Hide' }
                    - else
                      = link_to 'Show', hide_bank_account_path(bank_account),
                        method: :put, class: 'btn btn-info btn-sm', data: { disable_with: 'Show' }
                    = link_to 'Delete', bank_account, data: {confirm: 'Are you sure?'},
                      method: :delete, class: 'btn btn-danger btn-sm'
- else
  .alert.alert-warning No bank accounts

= content_for :sidebar
  = render 'home/settings'

app/views/bank_accounts/new.html.slim
.page-header
  h1 New bank account

== render 'form'

= link_to 'Back', bank_accounts_path

= content_for :sidebar
  = render 'home/settings'

app/views/bank_accounts/show.html.slim
.transactions_list
h1
  => @bank_account.to_s
  | transactions

= content_for :sidebar
  = render 'transactions/filter', url: bank_account_path(@bank_account)

= render 'transactions/transactions_table', transactions: @transactions