config/routes.rb
# frozen_string_literal: true

require 'api_constraints'

Rails.application.routes.draw do
  apipie
  devise_for :users, controllers: { registrations: 'user/registrations' }
  as :user do
    get 'user/profile' => 'users/registrations#edit', as: :user_profile
    put 'user/update_profile' => 'users/registrations#update_profile', as: :update_user_profile
    put 'user/update_account' => 'users/registrations#update', as: :update_user_account
    post 'invitation/create_user' => 'users/registrations#create_user_from_invitation', :as => 'create_user_from_invitation'
  end

  # You can have the root of your site routed with "root"
  root 'home#show'

  resources :organizations do
    member do
      put :switch
    end
  end
  get 'organization_wizzard/new_account', to: 'organization_wizzard#new_account', as: :new_account_organization
  get 'organization_wizzard/new_category', to: 'organization_wizzard#new_category', as: :new_category_organization
  post 'organization_wizzard/default_account', to: 'organization_wizzard#create_default_accounts', as: :default_account_organization
  post 'organization_wizzard/default_category', to: 'organization_wizzard#create_default_categories', as: :default_category_organization
  patch 'organization_wizzard/create_accounts', to: 'organization_wizzard#create_accounts', as: :create_accounts_organization
  patch 'organization_wizzard/create_categories', to: 'organization_wizzard#create_categories', as: :create_categories_organization
  resources :statistics, only: :index do
    get :income_by_customers, on: :collection, as: :income_by_customers
    get :expense_by_customers, on: :collection, as: :expense_by_customers
    get :income_by_categories, on: :collection, as: :income_by_categories
    get :expense_by_categories, on: :collection, as: :expense_by_categories
    get :totals_by_customers, on: :collection, as: :totals_by_customers
    get :balances_by_customers, on: :collection, as: :balances_by_customers
    get :balance, on: :collection, as: :balance
    get :customers_chart, on: :collection, as: :customers_chart
  end
  resources :bank_accounts, except: :show do
    put :hide, on: :member
    put :sort, on: :collection
  end
  resources :categories, except: :show
  resources :transactions,  only: %i[new create edit update destroy] do
    post :transfer, action: :create_transfer, on: :collection
  end
  resources :members, only: %i[index edit update destroy]
  resources :customers, except: :show do
    get 'autocomplete', on: :collection
  end
  resources :invoices do
    get 'unpaid', on: :collection
    resources :invoice_items, except: :show
  end
  resources :invitations, only: %i[new create]
  resources :organization_invitations, only: %i[new create destroy]
  get '/invitation/:token/accept' => 'invitations#accept', as: :accept_invitation
  get '/organization_invitation/:token/resend' => 'organization_invitations#resend', as: :resend_organization_invitation
  get '/unsubscribes/:token' => 'unsubscribes#activate', as: :activate_unsubscribe
  mount ActionCable.server => '/cable'

  # API
  namespace :api, defaults: { format: 'json' } do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      devise_for :users, skip: :sessions, controllers: { passwords: 'api/v1/passwords' }
      resources :users, only: %i[update destroy] do
        put :update_profile, on: :member
      end
      post :auth_token, to: 'auth_token#create'

      get :user_info, to: 'users#current'
      resources :currencies, only: %i[index]

      resources :organizations, only: %i[show index create update destroy] do
        resources :bank_accounts, only: %i[show index create update destroy] do
          get :visible, on: :collection
          put :position, action: :update_position, on: :member
        end
        resources :categories, only: %i[show index create update destroy]
        resources :customers, only: %i[show index create update destroy]
        resources :transactions, only: %i[show index create update destroy] do
          post :transfer, action: :create_transfer, on: :collection
          get :summary, on: :collection
        end
        resources :members, only: %i[index show update destroy] do
          get :current
        end
        get :member_info, to: 'members#current'
        put :last_visit, to: 'members#update_last_visit'
        resources :invoices, only: %i[index show create update destroy] do
          get :unpaid, on: :collection
          get 'unpaid/count' => :unpaid_count, on: :collection
        end
        get :total_balances, on: :member
        resources :organization_invitations, only: %i[index show create destroy] do
          post :resend, on: :member
        end
        resources :debtors, only: :index
        resource :statistic, only: [] do
          get :balance
          get :income_categories
          get :expense_categories
          get :income_customers
          get :expense_customers
          get :totals_by_customers
          get :balances_by_customers
          get :income_customers_by_months
          get :expense_customers_by_months
        end
      end
    end
  end
end

app/models/organization.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: organizations
#
#  id               :integer          not null, primary key
#  name             :string(255)      not null
#  created_at       :datetime
#  updated_at       :datetime
#  default_currency :string(255)      default("USD")
#

class Organization < ApplicationRecord
  include DateLogic

  has_many :members, inverse_of: :organization, dependent: :destroy
  has_many :owners,
    -> { where members: { role: 'owner' } }, through: :members, source: :user
  has_many :categories, dependent: :destroy
  has_many :users, through: :members
  has_many :bank_accounts, dependent: :destroy, inverse_of: :organization
  has_many :transactions, through: :bank_accounts, inverse_of: :organization
  has_many :invitations, through: :members, source: :created_invitations,
    inverse_of: :organization, dependent: :destroy
  has_many :customers, dependent: :destroy, inverse_of: :organization
  has_many :invoices, dependent: :destroy, inverse_of: :organization
  has_many :invoice_items, through: :invoices

  accepts_nested_attributes_for :bank_accounts, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :categories, reject_if: :all_blank, allow_destroy: true

  validates :name, presence: true

  def to_s
    name.truncate(30)
  end

  def ordered_curr
    currencies = bank_accounts.pluck(:currency).uniq.sort
    currencies.delete(default_currency)
    currencies.unshift(default_currency)
  end

  def exchange_rates
    org_curr = ordered_curr
    org_rates = []
    org_curr.each_with_index do |curr, i|
      org_curr[(i + 1)..-1].each do |to_curr|
        org_rates << curr + '_TO_' + to_curr
        org_rates << to_curr + '_TO_' + curr
      end
    end

    Money.default_bank.rates.deep_dup.keep_if do |curr_to_curr, _value|
      org_rates.any? do |org_rate|
        curr_to_curr == org_rate
      end
    end
  end

  def total_balances
    bank = Money.default_bank
    balances = []
    total_amount = Money.new(0, default_currency)
    Dictionaries.currencies.each do |currency|
      total = bank_accounts.total_balance(currency)
      total_amount += total.exchange_to(default_currency)
      balances <<
        if currency != default_currency
          {
            total:      total,
            ex_total:   total.exchange_to(default_currency),
            currency:   currency,
            rate:       bank.get_rate(total.currency, default_currency).round(4),
            updated_at: bank.rates_updated_at,
          }
        else
          {
            total:      total,
            ex_total:   nil,
            currency:   currency,
            rate:       nil,
            updated_at: nil,
          }
        end
    end
    balances.unshift({ total_amount: total_amount, default_currency: default_currency })
  end

  def find_customer_name_by_id(customer_id)
    customers.find(customer_id).to_s
  rescue StandardError
    ''
  end

  def invoice_debtors
    debtors_ids = invoices.unpaid.pluck(:customer_id).uniq
    Customer.where(id: debtors_ids)
  end

  def total_invoice_debt
    Debts::OrganizationDebt.new(self).total.format
  end
end

app/controllers/api/v1/organizations_controller.rb
# frozen_string_literal: true

class Api::V1::OrganizationsController < Api::V1::BaseController
  before_action :set_organization, only: %i[show update destroy total_balances]
  before_action :authorize_organization, only: %i[update destroy total_balances]

  def_param_group :organization do
    param :organization, Hash, required: true, action_aware: true do
      param :name, String, 'Name of the organization', required: true
      param :default_currency, String, 'Default currency for the organization'
    end
  end

  api :GET, '/organizations', 'Return organizations associated with the current user'
  def index
    @organizations = current_user.organizations
    render json: @organizations
  end

  api :GET, '/organizations/:id', 'Return organization'
  def show
    render json: @organization
  end

  api :POST, '/organizations', 'Create organization'
  param_group :organization, Api::V1::OrganizationsController
  def create
    @organization = current_user.organizations.build(organization_params)

    if @organization.save
      @organization.members.create(user: current_user, role: 'owner')
      render json: @organization
    else
      render json: @organization.errors, status: :unprocessable_entity
    end
  end

  api :PUT, '/organizations/:id', 'Update organization'
  param_group :organization, Api::V1::OrganizationsController
  def update
    if @organization.update(organization_params)
      render json: @organization
    else
      render json: @organization.errors, status: :unprocessable_entity
    end
  end

  api :DELETE, '/organizations/:id', 'Destroy organization'
  def destroy
    if @organization.destroy
      render json: @organization
    else
      render json: @organization.errors, status: :unprocessable_entity
    end
  end

  api :GET, 'organizations/:id/total_balances', 'Return total balances'
  def total_balances
  end

  private

  def set_organization
    @organization = current_user.organizations.find(params[:id])
  end

  def authorize_organization
    authorize @organization
  end

  def organization_params
    params.fetch(:organization, {}).permit(:name, :default_currency)
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  layout 'settings'
  before_action :find_organization, only: [:show, :edit, :update,
    :destroy, :switch]
  before_action :authorize_organization, only: [:show, :edit, :update, :destroy]

  def index
    @organizations = current_user.organizations
  end

  def show
    session[:current_organization_id] = @organization.id
    @bank_accounts = @organization.bank_accounts.positioned
  end

  def new
    @organization = Organization.new
  end

  def edit
  end

  def create
    @organization = Organization.new(organization_params)

    if @organization.save
      Member.create(user: current_user, organization: @organization, role: 'owner')
      if current_organization
        session[:current_organization_id] = @organization.id
      end
      redirect_to new_account_organization_path,
        notice: 'Organization was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @organization.update(organization_params)
      redirect_to @organization, notice: 'Organization was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @organization.destroy
    redirect_to organizations_url, notice: 'Organization was successfully removed.'
  end

  def switch
    if request.referrer == organization_url(current_organization)
      session[:current_organization_id] = @organization.id
      redirect_to organization_url(@organization.id)
    else
      session[:current_organization_id] = @organization.id
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def find_organization
    @organization = current_user.organizations.find(params[:id])
  end

  def authorize_organization
    authorize @organization
  end

  def organization_params
    params.require(:organization).permit(:name, :default_currency)
  end
end

app/views/organizations/_form.html.slim
.row
  .col-sm-6
    = simple_form_for(@organization) do |f|
      = f.error_notification

      .form-inputs
        = f.input :name, autofocus: true
        = f.input :default_currency, collection: Dictionaries.currencies,
          prompt: 'Select default currency'

      .form-actions
        = f.button :submit_with_disable, class: 'btn-primary'

app/views/organizations/edit.html.slim
.page-header
  h1 Editing organization

== render 'form'

=> link_to 'Show', @organization
'|
= link_to 'Back', :back

= content_for :sidebar
  = render 'home/settings'

app/views/organizations/index.html.slim
.page-header
  .pull-right
    = link_to 'New Organization', new_organization_path, class: 'btn btn-success'
  h1 Listing organizations

- if @organizations.present?
  table.table.table-stripped.table-hover
    thead
      tr
        th Name
        th Owners
        th
    tbody
      - @organizations.each do |organization|
        tr
          td = organization
          td = organization.owners.map(&:email).join(', ')
          td
            .btn-toolbar
              .btn-group.pull-right
                = link_to 'Show', organization, class: 'btn btn-default btn-sm'
                - if policy(organization).edit?
                  = link_to 'Edit', edit_organization_path(organization),
                    class: 'btn btn-default btn-sm'
                - if policy(organization).destroy?
                  = link_to 'Delete', organization, method: :delete,
                    data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm'
              - unless current_organization == organization
                .btn-group.pull-right id=dom_id(organization, :switch)
                  = button_to 'Switch', switch_organization_path(organization),
                    class: 'btn btn-primary btn-sm', method: :put
- else
  .alert.alert-warning No organizations

= content_for :sidebar
  = render 'home/settings'

app/views/organizations/new.html.slim
.page-header
  h2 New organization

= render 'form'

= link_to 'Back', organizations_path

= content_for :sidebar
  = render 'home/settings'

app/views/organizations/new_account.html.slim
.page-header
  h2 New organization bank account

.row.previous_buttons
  .col-sm-6
    p
      ' Bank account will be created by default (with default currency)
      br
      br
      = link_to 'Create default Bank account', default_account_organization_path(@organization.id), class: 'btn btn-primary'
  .col-sm-6
    p
      ' But you can create it manually
      br
      br
      = link_to 'Create manually', new_bank_account_path, class: 'btn btn-primary new_account', remote: true

.row
  .col-sm-12.new_account_form

.row.hidden.next_step_wrapper
  .col-sm-12
    .alert.alert-success
      ' Bank account was created successfully!
  .col-sm-3.offset-sm-1
      = link_to 'Create another', new_bank_account_path, class: 'btn btn-primary new_account', remote: true
  .col-sm-8
      = link_to 'Next step', new_category_organization_path(@organization), class: 'btn btn-success'

= content_for :sidebar
  = render 'home/settings'

app/views/organizations/new_category.html.slim
.page-header
  h2 New organization categories.

.row.previous_buttons
  .col-sm-6
    p
      ' Categories will be created by default
      br
      br
      = link_to 'Create default Categories', default_category_organization_path(@organization.id), class: 'btn btn-primary'

  .col-sm-6
    p
      ' But you can create it manually
      br
      br
      = link_to 'Create manually', new_category_path, class: 'btn btn-primary new_category', remote: true

.row
  .col-sm-12.new_category_form

.row.hidden.next_step_wrapper
  .col-sm-12
    .alert.alert-success
      ' Category was created successfully!
  .col-sm-3.offset-sm-1
      = link_to 'Create another', new_category_path, class: 'btn btn-primary new_category', remote: true
  .col-sm-8
      = link_to 'Finish', organization_finish_path(@organization), class: 'btn btn-success'

= content_for :sidebar
  = render 'home/settings'

app/views/organizations/show.html.slim
.page-header
  h1
    = link_to 'Organizations', organizations_path
    = "/#{params[:id]}"

p
  strong Name:
  =< @organization

.btn-group
  = link_to 'Back', organizations_path, class: 'btn btn-default btn-sm'
  - if policy(@organization).edit?
    = link_to 'Edit', edit_organization_path(@organization), class: 'btn btn-default btn-sm'
  - if policy(@organization).destroy?
    = link_to 'Delete', organization_path(@organization), method: 'delete', data: {confirm: 'Are you sure?'}, class: 'btn btn-danger btn-sm'

= content_for :sidebar
  = render 'home/settings'

app/views/organizations/show.js.erb
$('.bank-accounts').html("<%=j render partial: 'bank_accounts/bank_accounts', locals: { bank_accounts: @bank_accounts } %>");
$('.paginator').html("<%=j paginate(@bank_accounts, remote: true) %>");