config/routes.rb
# frozen_string_literal: true

require 'api_constraints'

Rails.application.routes.draw do
  apipie
  devise_for :users, controllers: { registrations: 'user/registrations' }
  as :user do
    get 'user/profile' => 'users/registrations#edit', as: :user_profile
    put 'user/update_profile' => 'users/registrations#update_profile', as: :update_user_profile
    put 'user/update_account' => 'users/registrations#update', as: :update_user_account
    post 'invitation/create_user' => 'users/registrations#create_user_from_invitation', :as => 'create_user_from_invitation'
  end

  # You can have the root of your site routed with "root"
  root 'home#show'

  resources :organizations do
    member do
      put :switch
    end
  end
  get 'organization_wizzard/new_account', to: 'organization_wizzard#new_account', as: :new_account_organization
  get 'organization_wizzard/new_category', to: 'organization_wizzard#new_category', as: :new_category_organization
  post 'organization_wizzard/default_account', to: 'organization_wizzard#create_default_accounts', as: :default_account_organization
  post 'organization_wizzard/default_category', to: 'organization_wizzard#create_default_categories', as: :default_category_organization
  patch 'organization_wizzard/create_accounts', to: 'organization_wizzard#create_accounts', as: :create_accounts_organization
  patch 'organization_wizzard/create_categories', to: 'organization_wizzard#create_categories', as: :create_categories_organization
  resources :statistics, only: :index do
    get :income_by_customers, on: :collection, as: :income_by_customers
    get :expense_by_customers, on: :collection, as: :expense_by_customers
    get :income_by_categories, on: :collection, as: :income_by_categories
    get :expense_by_categories, on: :collection, as: :expense_by_categories
    get :totals_by_customers, on: :collection, as: :totals_by_customers
    get :balances_by_customers, on: :collection, as: :balances_by_customers
    get :balance, on: :collection, as: :balance
    get :customers_chart, on: :collection, as: :customers_chart
  end
  resources :bank_accounts, except: :show do
    put :hide, on: :member
    put :sort, on: :collection
  end
  resources :categories, except: :show
  resources :transactions,  only: %i[new create edit update destroy] do
    post :transfer, action: :create_transfer, on: :collection
  end
  resources :members, only: %i[index edit update destroy]
  resources :customers, except: :show do
    get 'autocomplete', on: :collection
  end
  resources :invoices do
    get 'unpaid', on: :collection
    resources :invoice_items, except: :show
  end
  resources :invitations, only: %i[new create]
  resources :organization_invitations, only: %i[new create destroy]
  get '/invitation/:token/accept' => 'invitations#accept', as: :accept_invitation
  get '/organization_invitation/:token/resend' => 'organization_invitations#resend', as: :resend_organization_invitation
  get '/unsubscribes/:token' => 'unsubscribes#activate', as: :activate_unsubscribe
  mount ActionCable.server => '/cable'

  # API
  namespace :api, defaults: { format: 'json' } do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      devise_for :users, skip: :sessions, controllers: { passwords: 'api/v1/passwords' }
      resources :users, only: %i[update destroy] do
        put :update_profile, on: :member
      end
      post :auth_token, to: 'auth_token#create'

      get :user_info, to: 'users#current'
      resources :currencies, only: %i[index]

      resources :organizations, only: %i[show index create update destroy] do
        resources :bank_accounts, only: %i[show index create update destroy] do
          get :visible, on: :collection
          put :position, action: :update_position, on: :member
        end
        resources :categories, only: %i[show index create update destroy]
        resources :customers, only: %i[show index create update destroy]
        resources :transactions, only: %i[show index create update destroy] do
          post :transfer, action: :create_transfer, on: :collection
          get :summary, on: :collection
        end
        resources :members, only: %i[index show update destroy] do
          get :current
        end
        get :member_info, to: 'members#current'
        put :last_visit, to: 'members#update_last_visit'
        resources :invoices, only: %i[index show create update destroy] do
          get :unpaid, on: :collection
          get 'unpaid/count' => :unpaid_count, on: :collection
        end
        get :total_balances, on: :member
        resources :organization_invitations, only: %i[index show create destroy] do
          post :resend, on: :member
        end
        resources :debtors, only: :index
        resource :statistic, only: [] do
          get :balance
          get :income_categories
          get :expense_categories
          get :income_customers
          get :expense_customers
          get :totals_by_customers
          get :balances_by_customers
          get :income_customers_by_months
          get :expense_customers_by_months
        end
      end
    end
  end
end

app/controllers/api/v1/transactions_controller.rb
# frozen_string_literal: true

module Api::V1
  class TransactionsController < BaseOrganizationController
    before_action :set_transaction, only: %i[show update destroy]

    def_param_group :transaction do
      param :transaction, Hash, required: true, action_aware: true do
        param :amount, Float, 'Amount', required: true
        param :category_id, Integer, 'Category ID', required: true
        param :bank_account_id, Integer, 'Bank Account ID', required: true
        param :customer_id, Integer, 'Customer ID'
        param :invoice_id, Integer, 'Invoice ID'
        param :comment, String, 'Comment'
        param :date, Date, 'Date of creation', required: true
        param :reference_id, Integer, 'Reference bank account ID'
        param :comission, Integer, 'Comission'
        param :transfer_out_id, Integer, 'Transfer out ID'
        param :leave_open, [true, false], 'Leave open'
      end
    end

    def_param_group :transfer do
      param :transfer, Hash, required: true, action_aware: true do
        param :amount, Float, 'Amount', required: true
        param :comission, Float, 'Comission'
        param :exchange_rate, Float, 'Exchange Rate'
        param :bank_account_id, Integer, 'Bank Account ID', required: true
        param :comment, String, 'Comment'
        param :date, Date, 'Date of creation', required: true
        param :reference_id, Integer, 'Reference bank account ID'
        param :comission, Integer, 'Comission'
      end
    end

    api :GET, '/organizations/:organization_id/transactions', 'Return transactions'
    def index
      authorize :transaction

      @q = current_organization.transactions.ransack(params[:q])
      @q.sorts = ['date desc', 'created_at desc'] if @q.sorts.blank?

      @transactions = @q.result
      @transactions = @transactions.without_out([*@q.bank_account_id_eq])
      @transactions = @transactions.page(params[:page]).per(30)
    end

    def summary
      authorize :transaction

      @q = current_organization.transactions.ransack(params[:q])
      @q.sorts = ['date desc', 'created_at desc'] if @q.sorts.blank?

      @summary = TransactionsSummary.new(@q.result, current_organization.default_currency)

      render json: TransactionsSummarySerializer.new(@summary)
    end

    api :GET, '/organizations/:organization_id/transactions/:id', 'Return transaction'
    def show
    end

    api :POST, '/organizations/:organization_id/transactions', 'Create transaction'
    param_group :transaction, TransactionsController
    def create
      authorize :transaction

      @transaction = Transaction.new transaction_params.except(:amount)
      bank_account = current_organization.bank_accounts.find_by(id: transaction_params[:bank_account_id])
      @transaction.bank_account = bank_account
      @transaction.amount = transaction_params[:amount]&.to_d
      @transaction.created_by = current_user
      if @transaction.save
        render :show
      else
        render json: @transaction.errors.messages, status: :unprocessable_entity
      end
    end

    api :POST, '/organizations/:organization_id/transactions/transfer', 'Create transfer'
    param_group :transfer, TransactionsController
    def create_transfer
      authorize :transaction

      @transfer = Transfer.new(transfer_params)
      @transfer.created_by = current_user
      if @transfer.save
        @inc_transaction = @transfer.inc_transaction
        @out_transaction = @transfer.out_transaction
        @transaction = @inc_transaction
        render :show
      else
        render json: @transfer.errors.messages, status: :unprocessable_entity
      end
    end

    api :PUT, '/organizations/:organization_id/transactions/:id', 'Update transaction'
    param_group :transaction, TransactionsController
    def update
      if @transaction.update(transaction_params)
        render :show
      else
        render json: @transaction.errors, status: :unprocessable_entity
      end
    end

    api :DELETE, '/organizations/:organization_id/transactions/:id', 'Destroy transaction'
    def destroy
      @transaction.destroy
    end

    private

    def set_transaction
      @transaction = current_organization.transactions.find(params[:id])
      authorize @transaction
    end

    def transaction_params
      params.fetch(:transaction, {}).permit(:amount, :category_id, :bank_account_id,
        :comment, :comission, :reference_id, :customer_id, :customer_name, :date,
        :invoice_id, :leave_open, :transfer_out_id,
        transfer_out_attributes: %i[
          id amount category_id bank_account_id comment comission customer_id date
        ])
    end

    def transfer_params
      params.fetch(:transfer, {}).permit(:amount, :bank_account_id, :reference_id,
        :comment, :comission, :exchange_rate, :date, :calculate_sum)
    end
  end
end

app/controllers/transactions_controller.rb
# frozen_string_literal: true

class TransactionsController < ApplicationController
  before_action :require_organization
  before_action :redirect_for_not_ready_organization
  before_action :set_transaction, only: %i[edit update destroy]
  before_action :set_invoice, only: %i[new]
  after_action :update_last_viewed_at, only: %i[create create_transfer]

  def new
    if params[:copy_transaction_id].present?
      @transaction = current_organization.transactions.find(params[:copy_transaction_id])
      @transaction = @transaction.dup

      if @transaction.transfer?
        @transfer = Transfer.new(
          amount:          @transaction.transfer_out.amount,
          bank_account_id: @transaction.transfer_out.bank_account_id,
          reference_id:    @transaction.bank_account_id,
          comission:       @transaction.transfer_out.comission,
          comment:         @transaction.comment,
          date:            @transaction.date,
          calculate_sum:   @transaction.amount
        )
      else
        @transaction.amount = @transaction.amount.abs
        @transaction.date   = Date.current
        @transfer = Transfer.new
      end
    else
      @q = current_organization.transactions.ransack(session[:filter])
      if @invoice.present?
        @transaction = Transaction.new(customer_id: @invoice.customer_id,
          customer_name: current_organization.find_customer_name_by_id(@invoice.customer_id),
          amount: @invoice.amount.to_d, invoice: @invoice, bank_account_id: @invoice.bank_account_id)
      else
        @transaction = Transaction.new
        @transfer = Transfer.new
      end
    end
  end

  def create
    @transaction = Transaction.new(transaction_params)
    check_relation_to_curr_org(:transaction)
    @transaction.created_by = current_user
    @transaction.save
    @transaction_dup = @transaction.dup if @transaction.leave_open == '1'
  end

  def create_transfer
    @transfer = Transfer.new(transfer_params)
    check_relation_to_curr_org(:transfer)
    @transfer.created_by = current_user
    if @transfer.save
      @inc_transaction = @transfer.inc_transaction
      @out_transaction = @transfer.out_transaction
      @transfer_dup = @transfer.dup if @transfer.leave_open == '1'
    end
  end

  def edit
  end

  def update
    @success = @transaction.update(transaction_params)
  end

  def destroy
    @transaction.destroy
  end

  private

  def check_relation_to_curr_org(trans)
    tparams = params[trans]
    trans = @transaction || @transfer
    curr_bank_accounts = current_organization.bank_accounts
    trans.bank_account_id = curr_bank_accounts.find_by(id: tparams[:bank_account_id]).try(:id)
    trans.category_id = current_organization.categories.find_by(id: tparams[:category_id]).try(:id) if tparams[:category_id]
    trans.reference_id = curr_bank_accounts.find_by(id: tparams[:reference_id]).try(:id) if tparams[:reference_id]
    trans.customer_id = current_organization.customers.find_by(name: tparams[:customer_name]).try(:id) if trans == @transaction

    if trans == @transaction && trans.customer_id.nil? && tparams[:invoice_id].present?
      trans.customer_id = current_organization.customers.find_by(
        id: current_organization.invoices.find_by(id: tparams[:invoice_id]).try(:customer_id)
      ).try(:id)
    end
  end

  def set_invoice
    @invoice = current_organization.invoices.find(params[:invoice_id]) if params[:invoice_id]
  end

  def set_transaction
    @transaction = current_organization.transactions.find(params[:id])
  end

  def transaction_params
    params.require(:transaction).permit(
      :amount, :category_id, :bank_account_id, :comment, :comission,
      :reference_id, :customer_id, :customer_name, :date, :invoice_id, :leave_open,
      transfer_out_attributes: %i[id amount category_id bank_account_id comment comission customer_id date]
    )
  end

  def transfer_params
    params.require(:transfer).permit(
      :amount, :bank_account_id, :reference_id,
      :comment, :comission, :exchange_rate, :date, :calculate_sum, :leave_open,
    )
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.slim
= simple_form_for(transaction, remote: true, html: { class: 'form-horizontal transaction' }, wrapper: :horizontal_form, wrapper_mappings: { boolean: :checkbox }) do |f|
  = f.error_notification
  .alert.alert-success role="alert" style='display: none;' Transaction was created successfully!

  = f.input :amount, input_html: { value: f.object.amount == 0 ? nil : f.object.amount, maxlength: 25 }

  - if f.object.category.try(:system?)
    = f.input :category, disabled: true
  - elsif params[:action] == 'new' || params[:action] == 'create'
    = f.association :category, as: :select,
      collection: current_organization.categories.where(type: type),
      prompt: 'Category', value_method: :id,
      selected: @q.nil? ? f.object.category_id \
        : (@q.category_id_in ? @q.category_id_in : nil),
      required: true
  - else
    = f.association :category, as: :select,
      collection: current_organization.categories.where(type: f.object.category.type),
      prompt: 'Category', value_method: :id,
      selected: f.object.category_id,
      required: true

  - if transaction.transfer? && (params[:action] == 'edit' || params[:action] == 'update')
    = f.simple_fields_for :transfer_out, transaction.transfer_out do |t|
      = t.input :amount, input_html: { id: 'transfer-out-amount', maxlength: 25 }, label: 'From amount'
      = t.input :category_id, as: :hidden
      = t.input :customer_id, as: :hidden
      = t.input :comment, as: :hidden
      = t.input :date, as: :hidden
      = t.input :bank_account, disabled: true
  - elsif @invoice.present? || f.object.invoice_id
    = f.input :customer_name, disabled: true,
      input_html: { value: current_organization.find_customer_name_by_id(f.object.customer_id) }
  - else
    = f.input :customer_name, input_html: { class: 'customer-select2', data: { url: autocomplete_customers_path,
      placeholder: 'Customer',
      value: @q.nil? ? current_organization.find_customer_name_by_id(f.object.customer_id) \
        : (@q.customer_id_eq ? current_organization.find_customer_name_by_id(@q.customer_id_eq) : nil) } }

  - if transaction.transfer? && (params[:action] == 'edit' || params[:action] == 'update')
    = f.input :bank_account, disabled: true
  - elsif @invoice.present? || f.object.invoice_id
    = f.association :bank_account, as: :grouped_select,
      collection: current_organization.bank_accounts.by_currency(@invoice.present? ? @invoice.currency \
      : current_organization.invoices.find_by(id: f.object.invoice_id).try(:currency)).visible.positioned.grouped_by_currency(current_organization.default_currency),
      prompt: 'Bank account', group_method: :last, label: transaction.transfer? ? 'To' : 'Bank account',
      selected: f.object.bank_account_id
  - elsif f.object.bank_account.nil? || f.object.bank_account.visible?
    = f.association :bank_account, as: :grouped_select,
      collection: current_organization.bank_accounts.visible.positioned.grouped_by_currency(current_organization.default_currency),
      prompt: 'Bank account', group_method: :last, label: transaction.transfer? ? 'To' : 'Bank account',
      selected: @q.nil? ? f.object.bank_account_id \
        : (@q.bank_account_id_eq && current_organization.bank_accounts.find(@q.bank_account_id_eq).visible? \
        ? @q.bank_account_id_eq : nil)
  - else
    = f.input :bank_account, disabled: true

  - if (@invoice.present? || f.object.invoice_id) && (params[:action] == 'new' || params[:action] == 'create')
    = f.input :comission, input_html: { class: 'comission' }
    = f.hint "Total amount: #{Money.new(f.object.amount.to_d*100 - (f.object.comission.present? ? f.object.comission.to_d*100 : 0),
      @invoice ? @invoice.currency : f.object.currency)}", id: 'total_amount_hint', class: 'col-md-9 col-md-offset-3'

  = f.input :comment

  = f.input :date, as: :string, placeholder: 'Date',
    input_html: { class: 'datepicker', value: f.object.date.present? ? l(f.object.date.to_date) : nil }, required: false

  - if transaction.invoice.present? && f.object.persisted?
    = link_to "Created from invoice", invoice_path(transaction.invoice), class: 'pull-right'

  = f.input :invoice_id, as: :hidden
  - unless transaction.persisted? || @invoice.present? || f.object.invoice_id
    = f.input :leave_open, as: :boolean, wrapper_html: { class: 'col-sm-6 pull-left' }, input_html: { id: "leave_open_#{type}" }

app/views/transactions/_modal_content.html.slim
.modal-header
  button type='button' class='close' data-dismiss='modal' aria-hidden='true' &nbsp;&times;
  h4.modal-title#modal_title Transaction
.modal-body
  .panel.with-nav-tabs
    .panel-heading
      ul.nav.nav-tabs#transaction_type
        li.income
          = link_to @transaction.transfer? ? 'Transfer' : 'Income', '#income', data: { toggle: 'tab', type: 'income' }
        li.expense
          = link_to @transaction.transfer_out? ? 'Transfer' : 'Expense', '#expense', data: { toggle: 'tab', type: 'expense' }
        li.transfer
          = link_to 'Transfer', '#transfer', data: { toggle: 'tab', type: 'transfer' }
    .panel-body
      .tab-content
        .tab-pane#income
          = render 'transactions/form', type: 'Income', transaction: @transaction
        .tab-pane#expense
          = render 'transactions/form', type: 'Expense', transaction: @transaction
        .tab-pane#transfer
          = render 'transactions/transfer_form', transfer: @transfer.present? ? @transfer : Transfer.new
.modal-footer
  button type='button' class='btn btn-default' data-dismiss='modal' Cancel
  button type='button' class='btn btn-primary' id='submit_btn' data-trans-id="#{@transaction.id}"
    = submit_title
  - if @transaction.persisted?
    = link_to 'Remove', transaction_path(@transaction), remote: true, method: :delete,
        data: { confirm: 'Are you sure?', disable_with: 'Removing...' }, class: 'btn btn-danger pull-left'
    = link_to 'Copy', new_transaction_path(copy_transaction_id: @transaction.id), remote: true, class: 'btn btn-info pull-left'

app/views/transactions/_modal_form.html.slim
.modal.fade#transaction_modal tabindex='-1' role='dialog' aria-labelledby='modal-title' aria-hidden='true' data-keyboard='true'
  .modal-dialog
    .modal-content#content

app/views/transactions/_no_transactions.html.slim
.alert.alert-warning
  | This is default page, you will see all transactions from your organization
  =<> current_organization.name
  | here. But there is no any data yet. Please
  =<> link_to 'add bank accounts', new_bank_account_path, class: 'alert-link'
  | and some transactions then.

app/views/transactions/_transaction.html.slim
- transaction = transaction.transfer_in if transaction.transfer_out? && transaction.transfer_in
tr.transaction id=dom_id(transaction) class=colorize_transaction(transaction) data-edit-url=edit_transaction_path(transaction)
  td.col-sm-2 = money_with_symbol transaction.amount

  td.col-sm-2.word-break
    = link_to transaction.category.to_s,
      root_path(q: (params_unsafe_hash[:q] || {}).merge(category_id_in: transaction.category.id)),
      data: { stop_propagation: true } if transaction.category
  td.col-sm-3.word-break
    - if transaction.transfer?
      => link_to transaction.transfer_out.try(:bank_account).to_s,
        root_path(q: (params_unsafe_hash[:q] || {}).merge(bank_account_id_in: transaction.transfer_out.bank_account.id)),
        data: { stop_propagation: true } if transaction.transfer_out.try(:bank_account)
      |->
      =< link_to transaction.bank_account.to_s,
        root_path(q: (params_unsafe_hash[:q] || {}).merge(bank_account_id_in: transaction.bank_account.id)),
        data: { stop_propagation: true } if transaction.bank_account
    - else
      = link_to transaction.bank_account.to_s,
        root_path(q: (params_unsafe_hash[:q] || {}).merge(bank_account_id_in: transaction.bank_account.id)),
        data: { stop_propagation: true } if transaction.bank_account
  td.col-sm-2.word-break
    = link_to transaction.customer.to_s,
      root_path(q: (params_unsafe_hash[:q] || {}).merge(customer_id_in: transaction.customer_id)),
      data: { stop_propagation: true } if transaction.customer_id
  td.col-sm-2.word-break.comment.hidden-xs = transaction.comment
  td.col-sm-1= I18n.l transaction.date

app/views/transactions/_transactions.html.slim
= link_to 'Add...', new_transaction_path, remote: true, class: 'btn btn-primary'

.transactions_list
  = render 'transactions/transactions_table', transactions: transactions

= render 'transactions/modal_form'

app/views/transactions/_transactions_table.html.slim
- if transactions.present?
  table.table.table-hover.transactions.responsive-table data-min=8 data-max=18
    thead
      tr
        td = sort_link(@q, :amount_cents, 'Amount')
        td = sort_link(@q, :category_name, 'Category')
        td = 'Account'
        td = sort_link(@q, :customer_name, 'Customer')
        td.hidden-xs = sort_link(@q, :comment)
        td = sort_link(@q, :date, default_order: :desc)
    tbody
      - if request.params[:q].present?
        .pull-right
          = link_to 'Download as .CSV', root_path(q: request.params[:q], format: :csv), class: 'btn btn-link', style: 'margin-top: 20px;'
      = render transactions
  .paginator.col-md-offset-5
    = paginate transactions, remote: true
- elsif params[:q].blank?
  = render 'transactions/no_transactions'
- else
  .alert.alert-warning
    | There is nothing found by your search terms. Please try again with another filters.

app/views/transactions/_transfer_form.html.slim
= simple_form_for(transfer, url: transfer_transactions_path, remote: true,
    html: { id: 'new_transfer_form', class: 'form-horizontal transfer' }, wrapper: :horizontal_form, wrapper_mappings: { boolean: :checkbox }) do |f|
  = f.error_notification
  .alert.alert-success role="alert" style='display: none;' Transfer was created successfully!
  - bank_accounts = current_organization.bank_accounts.visible.positioned.grouped_by_currency(current_organization.default_currency)
  = f.input :bank_account_id, as: :grouped_select, include_blank: 'From',
      collection: bank_accounts, group_method: :last, label: 'From'
  = f.input :reference_id, as: :grouped_select, include_blank: 'To',
      collection: bank_accounts, group_method: :last, label: 'To'
  = f.input :amount, input_html: { class: 'amount', maxlength: 25 }

  #rate_col.hidden
    = f.input :calculate_sum, placeholder: 'Sum', input_html: { maxlength: 25 }
    = f.input :exchange_rate, input_html: { class: 'rate' }
    = f.hint 'Default rate:', id: 'rate_hint', class: 'col-md-9 col-md-offset-3'

  = f.input :comission, input_html: { class: 'comission', maxlength: 10 }
  = f.input :comment
  = f.input :date, as: :string, placeholder: 'Date',
      input_html: { class: 'datepicker', value: f.object.date.present? ? l(f.object.date.to_date) : nil }
  - unless transfer.persisted?
    = f.input :leave_open, as: :boolean, wrapper_html: { class: 'col-sm-6 pull-left' }

app/views/transactions/create.js.erb
<% if @transaction.persisted? %>
  if ($('.transactions').size() == 0) {
    // need to reload because there is no ransack initialized & no transactions table
    location.reload();
  }
  else {
    var element_id = "#<%= dom_id(@transaction) %>";
    var element = "<%=j render('transactions/transaction', transaction: @transaction) %>";
    var sidebar = "<%= j render('home/sidebar') %>";
    var total_balance = "<%= j render('shared/layout/total_balance') %>";
    addTransactionToList(element_id, element, sidebar, total_balance);
    <% if @transaction.leave_open == '1' %>
      if ($(".tab-pane.active").attr('id') == 'income') {
        $(".tab-pane.active #new_transaction").replaceWith("<%=j render('transactions/form', type: 'Income', transaction: @transaction_dup) %>");
      }
      else {
        $(".tab-pane.active #new_transaction").replaceWith("<%=j render('transactions/form', type: 'Expense', transaction: @transaction_dup) %>");
      }
      function toggleAlert () {
        $('.tab-pane.active #new_transaction .alert-success').toggle(300);
      };
      toggleAlert();
      setTimeout(toggleAlert, 3000);
    <% else %>
      $('#transaction_modal').modal('hide');
      scrollTo($("#<%= dom_id(@transaction) %>"));
    <% end %>
  }
<% else %>
  if ($(".tab-pane.active").attr('id') == 'income') {
    $(".tab-pane.active #new_transaction").replaceWith("<%=j render('transactions/form', type: 'Income', transaction: @transaction) %>");
  }
  else {
    $(".tab-pane.active #new_transaction").replaceWith("<%=j render('transactions/form', type: 'Expense', transaction: @transaction) %>");
  }
<% end %>
$('#submit_btn').prop('disabled', false);

addTransactionFormMasks();

app/views/transactions/create_transfer.js.erb
<% unless @transfer.errors.any? %>
  var element_id = "#<%= dom_id(@inc_transaction) %>";
  var element = "<%=j render('transactions/transaction', transaction: @inc_transaction) %>";
  var sidebar = "<%= j render('home/sidebar') %>";
  var total_balance = "<%= j render('shared/layout/total_balance') %>";
  addTransactionToList(element_id, element, sidebar, total_balance);
  <% if @transfer.leave_open == '1' %>
    $("#new_transfer_form").replaceWith("<%=j render('transactions/transfer_form', transfer: @transfer_dup) %>");
    prepRateAndHints(exchange_rate = true);
    function toggleAlert () {
      $('.tab-pane.active #new_transfer_form .alert-success').toggle(300);
    };
    toggleAlert();
    setTimeout(toggleAlert, 3000);
  <% else %>
    $('#transaction_modal').modal('hide');
    scrollTo($("#<%= dom_id(@inc_transaction) %>"));
  <% end %>
<% else %>
  $("#new_transfer_form").replaceWith("<%=j render('transactions/transfer_form', transfer: @transfer) %>");
  <% if @transfer.currency_mismatch? %>
    $('#transfer_comission').parents('.col-sm-2').addClass('col-sm-1').removeClass('col-sm-2');
    $('#transfer_exchange_rate').parents('#rate_col').removeClass('hidden');
  <% end %>
<% end %>
$('#submit_btn').prop('disabled', false);
addTransferFormMasks();

app/views/transactions/destroy.js.erb
$("#<%= dom_id(@transaction) %>").remove();
$("#<%= dom_id(@transaction, 'edit_row') %>").remove();
$('#transaction_modal').modal('hide');
$("#sidebar").replaceWith("<%= j render('home/sidebar') %>");
$("#total_balance").replaceWith("<%= j render('shared/layout/total_balance') %>");

app/views/transactions/edit.js.erb
$('#content').html("<%= j render('transactions/modal_content') %>");

<% if @transaction.category.nil? || @transaction.category.type == 'Income' %>
  $('li.expense').remove();
  $('li.income').addClass('active');
  $('.tab-pane#income').addClass('active');
<% else %>
  $('li.income').remove();
  $('li.expense').addClass('active');
  $('.tab-pane#income').addClass('active');
<% end %>
$('li.transfer').remove();

$('#transaction_modal').modal('show');
addTransactionFormMasks();